import {StyleSheet} from 'react-native';
import {Colors, Fonts} from '../../../../utils/Constants';

export const styles = StyleSheet.create({
  homeHeader: {
    height: 50,
    flexDirection: 'row',
    //  backgroundColor: Colors.black,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    width: '100%',
  },
  bold_12_black: {
    fontFamily: Fonts.gilroy_Bold,
    fontSize: 12,
    color: Colors.black,
  },
  semiBold_12_black: {
    fontFamily: Fonts.gilroy_SemiBold,
    fontSize: 12,
    color: Colors.black,
  },
  needSomeHelpViewContainer: {
    borderRadius: 5,
    backgroundColor: '#EEF3F9',
    flexDirection: 'row',
    height: 60,
    marginTop: 30,
    marginHorizontal: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scheduleTextContainer: {
    marginHorizontal: 18,
    marginTop: 30,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  habitTextContainer: {
    marginHorizontal: 18,
    marginTop: 30,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  todayScheduleBtnStyle: {
    borderRadius: 7,
    borderWidth: 1,
    marginHorizontal: 18,
    marginTop: 15,
    padding: 15,
    borderColor: Colors.inputGrey,
  },
  emptyView: {
    backgroundColor: Colors.inputGrey,
    borderRadius: 7,
    marginTop: 5,
    marginHorizontal: 18,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 10,
  },
  shadowStyle: {
    shadowColor: '#171717',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.4,
    shadowRadius: 2,
  },
  mainContainer: {
    backgroundColor: Colors.white,
    marginHorizontal: 18,
    height: 54,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    padding: 14,
    borderRadius: 7,
    marginTop: 5,
    marginBottom: 5,
  },
  bold_12_black: {
    fontFamily: Fonts.gilroy_Bold,
    fontSize: 12,
    color: Colors.black,
  },
  bold_12_opacity: {
    fontFamily: Fonts.gilroy_SemiBold,
    fontSize: 10,
    color: Colors.black,
    opacity: 0.4,
  },
  coloredBar: {
    width: 3,
    height: 34,
    backgroundColor: Colors.pink,
    borderRadius: 3,
  },
  iconStyle: {
    width: 14,
    height: 14,
    padding: 6,
  },
  justifyView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
});
