export const HabitsScreenConstants ={
    HABITS:"Habits",
    TODAY:'Today',
    ASSIGNED_BY_TRAINER:'Assigned by Trainer',
    SELF_ASSIGNED:'Self Assigned',
    INACTIVE:'Inactive',
    PREVIOUS:'Previous',
    HABITS_DETAILS:'Habit Details',
    VIEW_DETAIL:'View details',
    MARK_AS_DONE:'Mark as done',
    REMOVE_HABIT:'Remove habit',
    DEACTIVATE_HABIT:'Deactivate habit',
    ADD_NEW:'Add New',
    DELETE_HABIT:'Delete habit',
    REACTIVATE_HABIT:'Re-activate habit',
    HABIT_NAME:'Habit Name',
    DESCRIPTION:'Description',
    FREQUENCY:"Frequency",
    ONE_TIME:'One Time',
    MULTIPLE:"Multiple",
    SAVE:"Save",
    ADD_NEW_HABIT:'Add New Habits',
    NAME_VALIDATION:'HabitName is required.',
    FREQUENCY_VALIDATION:'Frequency is required.',
    DESCRIPTION_VALIDATION:'Description is required.',
    TIME_SLOT:"Please select time slot"
}