export const homeConstants = {
  MY_ASSIGNMENTS: 'My Assignments',
  NEED_SOME_HELP: 'Need some help? Connect with us',
  TOOLS: 'Tools',
  TODAY_SCHEDULE: 'Today’s Schedule',
  HEADING1: 'Day 1 of 42: Bodyweight Only (Circuit)',
  TODAY_HABIT: 'Today’s Habits',
  PROGRAMS: 'Programs',
  NUTRITIONS: 'Nutritions',
  WORKOUTS: 'Workouts',
  FILES: 'Files',
  HABITS: 'Habits',
  FORMS: 'Forms',
  BMR: 'BMR\nCalculator',
  BMI: 'BMI\nCalculator',
  MACRO_NUTRIENTS: 'Macronutrients\nCalculator',
  BODY_FAT: 'Body Fat\nCalculator',
  RM_CALCULATOR: '1RM\nCalculator',
};

export const programConstants = {
  MALE_BODY: 'Male Body Weight',
  PROGRAM_NOT_STARTED: 'This Program is not started yet!',
  PROGRAM_STARTED: 'This Programs has started',
  PROGRAM_COMPLETED: 'This Programs has completed',
  START_PROGRAM: 'START PROGRAM',
  WEEKS: 'Weeks',
  LATEST_WEIGHT: 'Latest Weight',
  STARTING_WEIGHT: 'Starting Weight',
  WEIGHT_CHANGE: 'Weight Change',
  TRACKER_WORKOUT: 'Tracker (Workouts)',
  WORKOUTS: 'Workouts',
  NUTRITION: 'Nutrition',
  PROGRESS_PHOTO: 'Progress Photos',
  NO_PHOTO_UPLOADED_YET: 'No photo has been uploaded yet.',
  UPLOAD_PHOTOS: 'Upload Photos',
  START_DATE: 'Start Date',
  COMPLITION: 'Completion',
  DURATION: 'Duration',
  STARTING_WORK_NOW: 'Starting Workout Now?',
  FOLLOW_WORKOUT_TEMPLATE: 'Follow Workout Template?',
  TODAY_AM_WORKOUT: 'Today’s AM Workouts',
  TODAY_PM_WORKOUT: 'Today’s PM Workouts',
  START: 'Start',
  CURRENT_WORKOUT: 'Current Workout',
  FINISH_WORKOUTS: 'Finish Workout',
  WORKOUT_FINISHED: 'Workout Finished',
  AWESOME_YOU_HAVE_FINISHED: 'Awesome, you have finished the workout!',
  LIKE_TO_NOTE: 'Is there anything that you’d like to note about this?',
  FEEDBACK: 'Feedback',
  SAVE_AS_A_WORKOUT_TEMPLATE: 'Save as a workout template?',
  FINISH: 'Finish',
};
