export const ProgressRecordConstants = {
    MFM_JOURNEY: "MFM Journey",
    RECORD_PROGRESS: 'Record Progress',
    PROGRESS_INSIGHTS: "Progress Insights",
    WATER_CONSUMED: "Water Consumed",
    STEP_WALKED: 'Step Walked',
    BODY_MEASUREMENT: 'Body Weight Measurement',
    PROGRESS_PHOTO: 'Progress Photo',
    BODY_WEIGHT: 'Body Weight',
    HEIGHT: 'Height',
    CHEST_SIZE: 'Chest',
    WAIST_SIZE: 'Waist',
    CHEST: "Chest",
    MMHG: "mmHg",
    ML: "ml",
    BPM: "bpm",
    RIGHT_ARM_SIZE: 'Right Arm',
    BODY_FAT_MEASUREMENT: 'Body Fat Measurement',
    BODY_VITAL_STATS: 'Body Vital Stats',
    WEIGHT: 'Weight',
    NECK: 'Neck',
    FAT: "Total Body Fat%",
    HIP_SIZE: 'Hips',
    KG: "kg",
    CM: "cm",
    LEFT_ARM_SIZE: 'Left Arm',
    LEFT_THIGH_SIZE: 'Left thigh',
    RIGHT_THIGH_SIZE: 'Right thigh',
    LEFT_CALF_SIZE: 'Left Calf',
    Right_CALF_SIZE: 'Right Calf',
    SAVE_BODY_MEASUREMENT: 'Save Body Measurement',
    MEASUREMENT_TABLE: 'Measurement Table',
    DATE_MEASUREMENT_TAKEN: 'Date Measurement Taken',
    CHEST_RIGHT: 'Chest right',
    CHEST_LEFT: 'Chest left',
    TRICEP_LEFT: 'Tricep Left',
    TRICEP_RIGHT: 'Tricep Right',
    BICEP_LEFT: 'Bicep Left',
    BICEP_RIGHT: 'Bicep Right',
    SUPRAILIAC_LEFT: 'Suprailiac Left',
    SUPRAILIAC_RIGHT: 'Suprailiac Right',
    THIGH_LEFT: 'Thigh Left',
    THIGH_RIGHT: 'Thigh Right',
    BODY_FAT_LEFT: 'Fat Left',
    BODY_FAT_RIGHT: 'Fat Right',
    BODY_FAT_TOTAL: 'Fat',
    SAVE_BODY_FAT: 'Save Body Fat',
    SUBSCAPULARLEFT: 'Subscapular Left',
    SUBSCAPULARRIGHT: 'Subscapular Right',
    MIDAXILLARYLEFT: 'Midaxillary Left',
    MIDAXILLARYRIGHT: 'MidaxillaryRight',
    ABDOMINALLEFT: 'Abdominal Left',
    ABDOMINALRIGHT: 'Abdominal Right',
    BODY_FAT_TABLE: "Body Fat Table",
    FAT_RIGHT: "Fat Right",
    FAT_LEFT: 'Fat Left',
    CHEST_LEFT: 'Chest Left',
    CHEST_RIGHT: 'Chest Right',
    TRICEP_LEFT: 'Tricep Left',
    TRICEP_RIGHT: 'Tricep Right',
    BICEP_LEFT: 'Bicep Left',
    BICEP_RIGHT: 'Bicep Right',
    BODY_VITALS_STATS: 'Body Vital Stats',
    MUSCLEMASS: 'Muscle Mass',
    WATER: 'Water',
    HEIGHT: 'Height',
    HEARTRATE: 'Heart Rate',
    BLOOD_PRESSURE_SYSTOLIC: 'Blood Pressure Systolic',
    TRAINING_FREQUENCY: 'Training Frequency',
    SAVE_VITALS: 'Save Vitals',
    BLOOD_PRESSURE_DIASTOLIC: 'Blood Pressure Diastolic',
    BODY_TYPE: 'Body Type',
    MM: "mm",
    INCHES: "inches",
    CALCULATE_FAT: "Calculate Fat%"

}
export const ProgressPhotoConstants = {
    PROGRESS_PHOTOS: "Progress Photos",
    DATE: 'Date'
}